#
# Properties of an AISManager Computer
#
# minimum.distance=5
# collision.threat.distance=0.5

# was 1
minimum.distance=5
collision.threat.distance=0.5

# collision.threat.callback=nmea.computers.SpeakingCallback
# Warning: this next one is a singleton !
# Speaking, see lang below
# collision.threat.callback=nmea.computers.BufferedCollisionSingletonCallback
collision.threat.callback=nmea.computers.BufferedCollisionCallback
# contains properties dedicated to the callback above
collision.threat.callback.props=mux-configs/bcc.properties          
# collision.threat.callback=defaultx`