#
# Custom Collision Callback specific properties
# BCC: Boat Collision Callback
#
# collision.lang=EN
# collision.name=A.I.S. proximity
collision.lang=FR
collision.name=proximité A.I.S.
#
collision.verbose=true
polling.interval=10